apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-lb-virtualservice
  namespace: demo-istio-lb
spec:
  gateways:
    - demo-istio/nginx-lb-gateway
  hosts:
    - lab.k8s.io
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: nginx-lb-service.demo-istio.svc.cluster.local
            subset: V1
          weight: 20
        - destination:
            host: nginx-lb-service.demo-istio.svc.cluster.local
            subset: V2
          weight: 80